package com.mz.sanfen.greendaodemo.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mz.sanfen.greendaodemo.entity.User;
import com.mz.sanfen.greendaodemo.entity.Blog;

import com.mz.sanfen.greendaodemo.entity.UserDao;
import com.mz.sanfen.greendaodemo.entity.BlogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig blogDaoConfig;

    private final UserDao userDao;
    private final BlogDao blogDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        blogDaoConfig = daoConfigMap.get(BlogDao.class).clone();
        blogDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        blogDao = new BlogDao(blogDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Blog.class, blogDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        blogDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public BlogDao getBlogDao() {
        return blogDao;
    }

}
